spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/desktop_tdl?serverTimezone=Asia/Seoul
    username: desktop_user
    password: 1q2w3e4r5t!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
